# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.deploy.parameters]
stack_name = "apilambdamodular-api"
resolve_s3 = false
s3_bucket = "apilambdamodular-api"
s3_prefix = "apilambdamodular-api"
region = "sa-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

[sp.deploy.parameters]
stack_name = "apilambdamodular-api"
resolve_s3 = false
s3_bucket = "apilambdamodular-api"
s3_prefix = "apilambdamodular-api"
region = "sa-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

[us.deploy.parameters]
stack_name = "apilambdamodular-api-us"
resolve_s3 = false
s3_bucket = "apilambdamodular-api-us"
s3_prefix = "apilambdamodular-api-us"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"