AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 30
        MemorySize: 1024
        Architectures: [arm64]
        Tracing: Active
        Runtime: dotnet8

Resources:
    ApiGatewayModularHttpApi:
        Type: AWS::Serverless::HttpApi
        Properties:
          StageName: Prod

    OrcamentosApiLambdaModularFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: dotnet8
            CodeUri: ./ApiLambdaModular/
            Handler: ApiLambdaModular
            Environment:
                Variables:
                    LAMBDA_NAME: "OrcamentosApiLambdaModularFunction"
            Events:
                ApiEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref ApiGatewayModularHttpApi
                        Path: /orcamentos/{proxy+}
                        Method: ANY

    VendasApiLambdaModularFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: dotnet8
            CodeUri: ./ApiLambdaModular/
            Handler: ApiLambdaModular
            Environment:
                Variables:
                    LAMBDA_NAME: "VendasApiLambdaModularFunction"
            Events:
                ApiEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref ApiGatewayModularHttpApi
                        Path: /vendas/{proxy+}
                        Method: ANY

    ClientesApiLambdaModularFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: dotnet8
            CodeUri: ./ApiLambdaModular/
            Handler: ApiLambdaModular
            Environment:
                Variables:
                    LAMBDA_NAME: "ClientesApiLambdaModularFunction"
            Events:
                ApiEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref ApiGatewayModularHttpApi
                        Path: /clientes/{proxy+}
                        Method: ANY

    ProdutosApiLambdaModularFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: dotnet8
            CodeUri: ./ApiLambdaModular/
            Handler: ApiLambdaModular
            Environment:
                Variables:
                    LAMBDA_NAME: "ProdutosApiLambdaModularFunction"
            Events:
                ApiEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref ApiGatewayModularHttpApi
                        Path: /produtos/{proxy+}
                        Method: ANY

    ProxyApiLambdaModularFunction:
        Type: AWS::Serverless::Function
        Properties:
            Runtime: dotnet8
            CodeUri: ./ApiLambdaModular/
            Handler: ApiLambdaModular
            Environment:
                Variables:
                    LAMBDA_NAME: "ProxyApiLambdaModularFunction"
            Events:
                ApiEvent:
                    Type: HttpApi
                    Properties:
                        ApiId: !Ref ApiGatewayModularHttpApi
                        Path: /{proxy+}
                        Method: ANY
